/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> count(26,0);
        int n = t.size();
        
        for (int i = 0; i < n; ++i) {
            ++count[t[i]-'a'];
            
            if (i == n-1)
                break;
            
            --count[s[i]-'a'];
        }
        
        for (int i = 0; i < 26; ++i) {
            if (count[i])
                return i+'a';
        }
    }
};
